export const ASSET_LIST_SUCCESS = "ASSET_LIST_SUCCESS";
export const ASSET_LIST_LOADING = "ASSET_LIST_LOADING";
export const ASSET_LIST_ERROR = "ASSET_LIST_ERROR";

export const ASSETLIST_APPEND_SUCCESS = "ASSETLIST_APPEND_SUCCESS";
export const ASSETLIST_APPEND_LOADING = "ASSETLIST_APPEND_LOADING";
export const ASSETLIST_APPEND_ERROR = "ASSETLIST_APPEND_ERROR";

export const ASSETLIST_CLEAR = "ASSETLIST_CLEAR"
