export const ASSET_LIST_SUCCESS = "ASSET_LIST_SUCCESS";
export const ASSET_LIST_LOADING = "ASSET_LIST_LOADING";
export const ASSET_LIST_ERROR = "ASSET_LIST_ERROR";

export const ASSETLIST_APPEND_SUCCESS = "ASSETLIST_APPEND_SUCCESS";
export const ASSETLIST_APPEND_LOADING = "ASSETLIST_APPEND_LOADING";
export const ASSETLIST_APPEND_ERROR = "ASSETLIST_APPEND_ERROR";

export const ASSETLIST_CLEAR = "ASSETLIST_CLEAR"

export const SET_USD_BALANCE = "SET_USD_BALANCE"

export const WEEK_LOADING = "WEEK_LOADING"
export const WEEK_SUCCESS = "WEEK_SUCCESS"
export const WEEK_ERROR = "WEEK_ERROR"

export const USD_LOADING = "USD_LOADING"
export const USD_SUCCESS = "USD_SUCCESS"
export const USD_ERROR = "USD_ERROR"

